name: "Deploy-dev"

on:
    push:
        branches: [master]

jobs:
    deploy_to_develop:
        name: "Deploy on dev"
        runs-on: "ubuntu-latest"
        env:
            JWT_SECRET: ${{ secrets.JWT_SECRET }}
            MONGO_URL_CONNECT: ${{ secrets.MONGO_URL_CONNECT }}
        steps:
            - uses: actions/checkout@v2
            
            - name: setup_node
              uses: actions/setup-node@v2
              with:
                node-version: 12.x 
            
            - name: Install dependences
              run: yarn
              
            - name: Run buidl
              run: yarn build
              
           
            - name: Copy to Digital Ocean build
              uses: garygrossgarten/github-action-scp@release
              with:
                  local: dist
                  remote: test
                  host: ${{ secrets.HOST }}
                  privateKey: ${{ secrets.SSH_KEY }}
                  username: ${{ secrets.SSH_USER }}
                  password: ${{ secrets.PASSWORD }}
              
