name: "Deploy-dev"

on:
    push:
        branches: [develop]

jobs:
    deploy_to_develop:
        name: "Deploy on dev"
        runs-on: "ubuntu-latest"
        env:
            JWT_SECRET: ${{ secrets.JWT_SECRET }}
            MONGO_URL_CONNECT: ${{ secrets.MONGO_URL_CONNECT }}
        steps:
            - uses: actions/setup-node@v2
            - uses: actions/checkout@v2
